# MacPorts
#
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"

# bash completion
#
if [ -f /opt/local/etc/profile.d/bash_completion.sh ]; then
    . /opt/local/etc/profile.d/bash_completion.sh
fi

source ~/.bash_prompt

# locale
#
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
