source ~/.bashrc

##
# Your previous /Users/kuznetsov/.bash_profile file was backed up as /Users/kuznetsov/.bash_profile.macports-saved_2017-11-21_at_19:21:36
##

# MacPorts Installer addition on 2017-11-21_at_19:21:36: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.


# MacPorts Installer addition on 2017-11-22_at_10:08:54: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.

