# MacPorts
#
export PATH="/opt/local/bin:/opt/local/sbin:${PATH}"

# bash completion
#
if [ -f /opt/local/etc/profile.d/bash_completion.sh ]; then
    . /opt/local/etc/profile.d/bash_completion.sh
fi

source ~/.bash_prompt

# locale
#
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8


if [[ "${OSTYPE}" == "darwin"* ]]; then
    source ~/.bashrc.osx
fi

# viretualenv wrapper
#
export WORKON_HOME="${HOME}/.virtualenvs"
export PROJECT_HOME="${HOME}/work"
source /opt/local/bin/virtualenvwrapper.sh-3.6
