source "${HOME}/.commonrc.sh"

COLOR_LS_DIR="$(dirname $(gem which colorls))"
COLOR_LS_COMPLETE="${COLOR_LS_DIR}/tab_complete.sh"

autoload bashcompinit
bashcompinit
source "${COLOR_LS_COMPLETE}"

alias change-zsh="code-insiders ~/.zshrc"
alias update-zsh="source ~/.zshrc"
alias lc='colorls -lA --sd'

function precmd () {
    window_title="\\033]0;${PWD##*/}\\007"
    echo -ne "${window_title}"
}

fpath=($fpath "/Users/dmitry/.zfunctions")
autoload -U promptinit; promptinit
prompt spaceship
