set nocompatible

filetype plugin indent on

set encoding=utf-8
set fileencodings=utf-8

set number
set colorcolumn=81

syntax enable

set hidden

set autoindent
set tabstop=4
set softtabstop=4
set shiftwidth=4
set shiftround
set expandtab
set smarttab
set nowrap
set list
set backspace=indent,eol,start

" show trailing spaces
set listchars=tab:>.,trail:.,extends:#,nbsp:.

" golang people like tabs
augroup golang
    autocmd FileType go setlocal noexpandtab nolist
augroup END

set hlsearch
set incsearch
set ignorecase
set showmatch

" enable paste mode on <F2>
set pastetoggle=<F2>
