# Editors
export EDITOR=vim
export VISUAL=vim

# Enable colorized `ls` output.
# This is equivalent to the `-G` flag.
export CLICOLOR=1

# Add smlnj to path if it's installed.
# smlnj is Standard ML of New Jersey.
if [[ -d /usr/local/smlnj/bin ]]; then
    path+=(
        /usr/local/smlnj/bin
    )
fi  
